// Domain and print checks for the car-sale documentation; isolated synthetic data only.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),http=require('http'),os=require('os');
const root=path.resolve(__dirname,'..'),out=fs.mkdtempSync(path.join(os.tmpdir(),'kramurai-car-sale-'));
const server=http.createServer((req,res)=>{let f=path.join(root,new URL(req.url,'http://local').pathname);if(fs.existsSync(f)&&fs.statSync(f).isDirectory())f=path.join(f,'index.html');if(!fs.existsSync(f)){res.writeHead(404);return res.end();}res.setHeader('Content-Type',({'.html':'text/html','.css':'text/css','.js':'text/javascript','.svg':'image/svg+xml','.png':'image/png','.webp':'image/webp'})[path.extname(f)]||'application/octet-stream');fs.createReadStream(f).pipe(res);});
(async()=>{
 await new Promise(r=>server.listen(0,'127.0.0.1',r));const origin='http://127.0.0.1:'+server.address().port;
 const browser=await chromium.launch({executablePath:process.env.CHROMIUM_EXECUTABLE||undefined,args:['--no-sandbox','--disable-dev-shm-usage','--disable-gpu']});
 const context=await browser.newContext({viewport:{width:390,height:900},acceptDownloads:true,reducedMotion:'reduce'}),p=await context.newPage();const errors=[],external=[];
 p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(/^https?:/.test(r.url())&&!r.url().startsWith(origin))external.push(r.url())});
 p.setDefaultTimeout(10000);const results=[];results.push=function(...items){console.log('Passed: '+items.join(', '));return Array.prototype.push.apply(this,items)};const key='kramurai-car-sale-v1';
 const step=async n=>{while(Number(await p.locator('.step.active').getAttribute('data-step'))<n)await p.locator('#nextBtn').click();while(Number(await p.locator('.step.active').getAttribute('data-step'))>n){if(Number(await p.locator('.step.active').getAttribute('data-step'))===6)await p.locator('#finalBackBtn').click();else await p.locator('#backBtn').click();}if(n===6)await p.waitForFunction(()=>!document.querySelector('#finalPrintBtn').disabled)};
 try{
 await p.goto(origin+'/autoverkauf-dokumentieren/');const state=await p.evaluate(k=>JSON.parse(localStorage.getItem(k)),key);
 assert.equal(state.handover.status,'');assert.equal(state.payment.status,'');assert.equal(state.condition.accidents,'');assert.equal(state.condition.driveability,'');assert.equal(state.condition.defects,'');assert.equal(state.handover.vehicle,false);results.push('no-presumed-payment-handover-or-accident-free-status');assert(await p.getByRole('link',{name:'ADAC-Kaufvertrag öffnen',exact:true}).isVisible());assert((await p.locator('.contract-intro').innerText()).includes('nicht automatisch'));assert.equal(await p.locator('details[data-optional][open]').count(),0);results.push('contract-visible-before-first-step-and-optional-fields-collapsed');
 await p.locator('#itemName').fill('Musterfahrzeug');await step(6);let text=await p.locator('#summary').innerText();assert(text.includes('Noch nicht dokumentiert'));assert(!text.includes('Vollständig erhalten'));assert(!text.includes('keine Unfallschäden'));assert((await p.locator('#missingCheck').innerText()).includes('ersetzt ihn nicht'));results.push('incomplete-case-still-exportable-and-separate-contract-explained');
 await step(1);await p.locator('#serial').fill('WVWZZZTEST12345678');await p.locator('#seller').fill('Max Muster');await p.locator('#buyer').fill('Erika Beispiel');await p.locator('#mileage').fill('154800');await p.locator('#registration').fill('TEST AB 123');await p.locator('details[data-optional]').filter({has:p.locator('#firstRegistration')}).locator('summary').click();await p.locator('#firstRegistration').fill('2016-05-01');
 await step(2);await p.locator('#driveability').selectOption('Fahrbereit nach eigener Einschätzung');await p.locator('#defects').selectOption('Bekannte Mängel vorhanden');await p.locator('#accidents').selectOption('Keine verlässlichen Angaben');await p.locator('#conditionNote').fill('Kratzer hinten rechts; Warnmeldung dokumentiert. <img src=x onerror="window.__unsafe=true">');await p.locator('details[data-optional]').filter({has:p.locator('#repairs')}).locator('summary').click();await p.locator('#repairs').fill('Werkstattrechnung vom 01.10.2026 liegt vor. Eine erneute Prüfung ist noch geplant.');
 await step(3);await p.locator('[data-check="documents.partI"]').check();await p.locator('[data-check="accessories.extraWheels"]').check();await p.locator('#contractStatus').selectOption('Entwurf vorbereitet');
 const adac=p.getByRole('link',{name:'ADAC-Kaufvertrag öffnen'});assert.equal(await adac.getAttribute('href'),'https://www.adac.de/rund-ums-fahrzeug/auto-kaufen-verkaufen/gebrauchtwagenkauf/kfz-kaufvertrag/');assert((await adac.getAttribute('rel')).includes('noopener'));results.push('official-adac-link-no-embedded-third-party-contract');
 await step(4);const image=await p.evaluate(()=>{const c=document.createElement('canvas');c.width=800;c.height=600;const g=c.getContext('2d');g.fillStyle='#d6e8df';g.fillRect(0,0,800,600);g.fillStyle='#18554d';g.font='30px sans-serif';g.fillText('Kramurai: synthetisches Testfoto',50,100);return c.toDataURL('image/png').split(',')[1]});
 for(const type of ['overall','serial','odometer','damage','damage2','interior','accessories']){await p.locator('[data-photo="'+type+'"]').last().setInputFiles({name:'Testfoto.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await p.waitForFunction(t=>document.querySelector('[data-task="'+t+'"]').classList.contains('done'),type)}
 p.once('dialog',d=>d.dismiss());await p.locator('[data-remove-file="damage2"]').click();assert(await p.locator('[data-task="damage2"]').evaluate(e=>e.classList.contains('done')));
 p.once('dialog',d=>d.accept());await p.locator('[data-remove-file="damage2"]').click();await p.waitForFunction(()=>!document.querySelector('[data-task="damage2"]').classList.contains('done'));assert(await p.locator('[data-task="damage"]').evaluate(e=>e.classList.contains('done')));assert(await p.locator('[data-remove-file="damage2"]').isHidden());results.push('individual-photo-removal-confirmation-and-isolation');
 await p.locator('#addPhotoBtn').click();await p.locator('[data-photo="extra1"]').last().setInputFiles({name:'Seitenansicht.png',mimeType:'image/png',buffer:Buffer.from(image,'base64')});await p.waitForFunction(()=>document.querySelector('[data-task="extra1"]').classList.contains('done'));await p.locator('#photoNote-extra1').fill('Linke Seite: Kratzer dokumentiert. <img src=x onerror="window.__unsafe=true">');
 await p.locator('#addPhotoBtn').click();await p.locator('#photoNote-extra2').fill('Entfernter Fotoplatz');p.once('dialog',d=>d.accept());await p.locator('[data-remove-file="extra2"]').click();await p.waitForFunction(()=>!document.querySelector('[data-task="extra2"]'));assert(await p.locator('#addPhotoBtn').evaluate(e=>e===document.activeElement));assert(await p.locator('[data-task="extra1"]').isVisible());results.push('additional-photos-captions-and-targeted-slot-removal');

 await step(5);await p.locator('#price').fill('4.500,00');await p.locator('#amount').fill('500,00');await p.locator('#paymentStatus').selectOption('Vollständig erhalten');await p.locator('#handoverStatus').selectOption('Geplant');await p.locator('[data-check="handover.partI"]').check();await step(6);
 let hints=await p.locator('#missingCheck').innerText();assert(hints.includes('kleiner als'));assert(hints.includes('nicht als erfolgt'));text=await p.locator('#summary').innerText();assert(text.includes('4.500,00 €'));assert(text.includes('500,00 €'));assert.equal(await p.evaluate(()=>window.__unsafe),undefined);assert.equal(await p.locator('#summary img[src="x"]').count(),0);results.push('payment-and-handover-contradictions-reported-without-silent-correction');results.push('user-text-escaped-in-summary');assert(text.includes('Fahrbereit nach eigener Einschätzung'));assert(text.includes('Bekannte Mängel vorhanden'));assert(text.includes('Linke Seite: Kratzer'));assert((await p.locator('#documentChecks').textContent()).includes('kleiner als'));await p.emulateMedia({media:'print'});assert(await p.locator('#documentChecks').isVisible());await p.emulateMedia({media:'screen'});assert(await p.locator('#documentChecks').isHidden());results.push('independent-condition-and-printable-contradiction-notices');
 await p.locator('.case-manager summary').click();const exportPromise=p.waitForEvent('download');await p.locator('#backupExportBtn').click();const backup=await exportPromise;await backup.saveAs(path.join(out,'car-new.json'));const archive=JSON.parse(fs.readFileSync(path.join(out,'car-new.json')));assert.equal(archive.files.length,7);assert(archive.state.extraPhotos.extra1);assert(archive.state.photoNotes.extra1.includes('Kratzer'));const originalId=archive.state.caseId;
 await p.locator('#backupFile').setInputFiles(path.join(out,'car-new.json'));await p.waitForFunction(()=>document.querySelector('#backupStatus').textContent.includes('zusätzlicher Vorgang geöffnet'));await step(6);assert.equal(await p.locator('#summaryPhotos img').count(),7);assert((await p.locator('#summary').innerText()).includes('Linke Seite: Kratzer'));results.push('additional-photo-and-caption-backup-roundtrip');
 const legacy=JSON.parse(JSON.stringify(archive));delete legacy.state.extraPhotos;delete legacy.state.photoNotes;delete legacy.state.condition.driveability;delete legacy.state.condition.defects;legacy.state.condition.rating='Bekannte Mängel vorhanden';for(const key of ['coc','abe','digitalServices'])delete legacy.state.documents[key];for(const key of ['hu','service','invoices','coc','abe'])delete legacy.state.handover[key];legacy.files=legacy.files.filter(f=>!f.type.startsWith('extra'));
 await p.locator('#backupFile').setInputFiles({name:'legacy.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(legacy))});await p.waitForFunction(()=>document.querySelector('#backupStatus').textContent.includes('zusätzlicher Vorgang geöffnet')&&document.querySelector('#itemName').value==='Musterfahrzeug');await step(2);assert.equal(await p.locator('#defects').inputValue(),'Bekannte Mängel vorhanden');await step(6);assert.equal(await p.locator('#summaryPhotos img').count(),6);assert((await p.locator('#summary').innerText()).includes('Warnmeldung'));results.push('previous-version-backup-import-preserves-data-and-files');
 await p.locator('#caseSelect').selectOption(originalId);await p.waitForFunction(()=>document.querySelector('#finalPrintBtn').disabled===false);await step(5);await p.locator('#handoverStatus').selectOption('Erfolgt');await p.locator('#paymentStatus').selectOption('Zahlung offen');await p.locator('[data-check="handover.partII"]').check();await step(6);let problems=await p.locator('#documentChecks').textContent();assert(problems.includes('offener Zahlung'));assert(problems.includes('Fahrzeugbrief'));assert(problems.includes('beidseitig'));await p.emulateMedia({media:'print'});await p.pdf({path:path.join(out,'Autoverkauf_Pruefhinweise.pdf'),format:'A4',printBackground:true,margin:{top:'12mm',bottom:'12mm',left:'12mm',right:'12mm'}});await p.emulateMedia({media:'screen'});results.push('actual-handover-with-open-payment-and-released-title-flagged');
 await step(5);await p.locator('[data-check="handover.partII"]').uncheck();await p.locator('#handoverStatus').selectOption('Geplant');

 await step(5);await p.locator('#paymentStatus').selectOption('Anzahlung erhalten');await p.locator('[data-check="handover.partI"]').uncheck();await p.locator('#handoverDate').fill('2026-10-12');await p.locator('#handoverTime').fill('14:30');await p.locator('#handoverPlace').fill('Musterort');await step(6);hints=await p.locator('#missingCheck').innerText();assert(!hints.includes('kleiner als'));assert(!hints.includes('nicht als erfolgt'));
 await p.emulateMedia({media:'print'});await p.pdf({path:path.join(out,'Autoverkauf_Muster.pdf'),format:'A4',printBackground:true,margin:{top:'12mm',bottom:'12mm',left:'12mm',right:'12mm'}});await p.emulateMedia({media:'screen'});results.push('representative-seven-photo-pdf');
 const fixture=await context.newPage();await fixture.setContent('<h1>Synthetischer Zahlungsbeleg</h1><p>Testdatei – kein echter Zahlungseingang.</p>');const receipt=await fixture.pdf({format:'A4'});await fixture.close();
 await step(5);await p.locator('details[data-optional]').filter({has:p.locator('[data-attachment="receipt"]')}).locator('summary').click();await p.locator('[data-attachment="receipt"]').setInputFiles({name:'Testbeleg.pdf',mimeType:'application/pdf',buffer:receipt});await p.waitForFunction(()=>document.querySelector('[data-task="receipt"] .photo-status').textContent.includes('PDF gespeichert'));await step(6);const pending=p.waitForEvent('download');await p.getByRole('link',{name:'Original-PDF speichern',exact:true}).click();const download=await pending;await download.saveAs(path.join(out,'Beleg_Original.pdf'));assert.deepEqual(fs.readFileSync(path.join(out,'Beleg_Original.pdf')),receipt);assert.equal(await p.locator('#summaryPhotos img').count(),7);assert((await p.locator('#summary').innerText()).includes('Original-PDF separat beifügen: Testbeleg.pdf'));results.push('pdf-receipt-separate-download-with-original-bytes');
 await step(2);await p.locator('#conditionNote').fill(Array.from({length:45},(_,i)=>'Dokumentierter Punkt '+(i+1)+': längere Beschreibung einer Auffälligkeit und der noch ausstehenden Prüfung.').join('\n'));await step(6);await p.emulateMedia({media:'print'});await p.pdf({path:path.join(out,'Autoverkauf_Langtext.pdf'),format:'A4',printBackground:true,margin:{top:'12mm',bottom:'12mm',left:'12mm',right:'12mm'}});await p.emulateMedia({media:'screen'});results.push('long-text-pdf-page-breaks');
 for(const width of [320,360,390,520,768,1280]){await p.setViewportSize({width,height:900});for(const n of [1,3,4,5,6]){await step(n);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.equal(await p.evaluate(()=>[...document.querySelectorAll('img')].filter(e=>e.getAttribute('src')&&!e.complete).length),0)}await step(1);await p.screenshot({path:path.join(out,'Start-'+width+'.png'),fullPage:true})}results.push('six-width-layout-checks');

 const legacyContext=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});const legacyPage=await legacyContext.newPage();await legacyPage.addInitScript(({key,state})=>localStorage.setItem(key,JSON.stringify(state)),{key,state:{...legacy.state,currentStep:1}});await legacyPage.goto(origin+'/autoverkauf-dokumentieren/');assert.equal(await legacyPage.locator('#itemName').inputValue(),'Musterfahrzeug');await legacyPage.locator('#nextBtn').click();assert.equal(await legacyPage.locator('#defects').inputValue(),'Bekannte Mängel vorhanden');assert(await legacyPage.locator('details[data-optional]').filter({has:legacyPage.locator('#repairs')}).evaluate(e=>e.open));await legacyContext.close();results.push('previous-local-state-migration-and-populated-details-open');
 const minimalContext=await browser.newContext({viewport:{width:390,height:900},reducedMotion:'reduce'});const minimal=await minimalContext.newPage();await minimal.goto(origin+'/autoverkauf-dokumentieren/');await minimal.locator('#itemName').fill('Vorbereitung');for(let i=0;i<5;i++)await minimal.locator('#nextBtn').click();await minimal.waitForFunction(()=>!document.querySelector('#finalPrintBtn').disabled);assert(await minimal.locator('#documentChecks').evaluate(e=>e.hidden));assert.equal(await minimal.locator('.summary-row').count(),11);assert.equal(await minimal.locator('.photo-summary-card').count(),0);await minimal.emulateMedia({media:'print'});await minimal.pdf({path:path.join(out,'Autoverkauf_Vorbereitung.pdf'),format:'A4',printBackground:true,margin:{top:'12mm',bottom:'12mm',left:'12mm',right:'12mm'}});assert(await minimal.locator('#documentChecks').isHidden());await minimalContext.close();results.push('compact-preparation-pdf-without-premature-signed-contract-warning');
 assert.deepEqual(external,[]);assert.deepEqual(errors,[]);results.push('no-external-requests-or-javascript-errors');
 }finally{await browser.close();server.close();fs.writeFileSync(path.join(out,'checks.json'),JSON.stringify(results,null,2));console.log(JSON.stringify({checks:results,reportDirectory:out},null,2))}
})().catch(e=>{console.error(e);server.close();process.exitCode=1});
